# Data

RainFall data : Department of Meteorology - Sri Lanka.

Microwave link data: Dialog Axiata, Mobile network operator company [Sri Lanka]

THIS MODEL USES RSL_MIN VALUES AND FREQUNCY, PATH LENGTH AS THE FEATURES. THERE IS NO BASELINE CORRECTION FOR THIS MODEL

In [24]:
import pandas as pd
import pickle as pk
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import cross_val_score

In [3]:
data_file = pd.read_csv("/home/cmlare/Data/RF Data/Processed/2018-05-08 to 2018-05-15_integrated_classified.csv")
data_file_1 = pd.read_csv("/home/cmlare/Data/RF Data/Processed/2018-05-16 to 2018-05-23_integrated_classified.csv")
data_file_2 = pd.read_csv("/home/cmlare/Data/RF Data/Processed/2018-05-24 to 2018-05-31_integrated_classified.csv")
data_file_3 = pd.read_csv("/home/cmlare/Data/RF Data/Processed/2018-06-01 to 2018-06-10_integrated_classified.csv")

data_file = pd.concat([data_file, data_file_1, data_file_2, data_file_3])

In [9]:
data_file

date_time      ID                  PrecipStation  \
0       2018-05-05 00:00:00   513.0                 curw_IBATTARA2   
1       2018-05-05 00:00:00    37.0                 curw_IBATTARA2   
2       2018-05-05 00:00:00    70.0                 curw_IBATTARA2   
3       2018-05-05 00:00:00  2189.0                 curw_IBATTARA2   
4       2018-05-05 00:00:00  1706.0                 curw_IBATTARA2   
5       2018-05-05 00:00:00   173.0                 curw_IBATTARA2   
6       2018-05-05 00:00:00  1736.0                 curw_IBATTARA2   
7       2018-05-05 00:00:00  1738.0                 curw_IBATTARA2   
8       2018-05-05 00:00:00  1262.0                 curw_IBATTARA2   
9       2018-05-05 00:00:00  1295.0                 curw_IBATTARA2   
10      2018-05-05 00:00:00  1398.0                 curw_IBATTARA2   
11      2018-05-05 00:00:00   964.0                 curw_IBATTARA2   
12      2018-05-05 00:00:00   481.0                 curw_IBATTARA2   
13      2018-05-05 00:00:00   511.0                 curw_IBATTARA2   
14      2018-05-05 00:15:00   513.0                 curw_IBATTARA2   
15      2018-05-05 00:15:00    37.0                 curw_IBATTARA2   
16      2018-05-05 00:15:00    70.0                 curw_IBATTARA2   
17      2018-05-05 00:15:00  2189.0                 curw_IBATTARA2   
18      2018-05-05 00:15:00  1706.0                 curw_IBATTARA2   
19      2018-05-05 00:15:00   173.0                 curw_IBATTARA2   
20      2018-05-05 00:15:00  1736.0                 curw_IBATTARA2   
21      2018-05-05 00:15:00  1738.0                 curw_IBATTARA2   
22      2018-05-05 00:15:00  1262.0                 curw_IBATTARA2   
23      2018-05-05 00:15:00  1295.0                 curw_IBATTARA2   
24      2018-05-05 00:15:00  1398.0                 curw_IBATTARA2   
25      2018-05-05 00:15:00   964.0                 curw_IBATTARA2   
26      2018-05-05 00:15:00   481.0                 curw_IBATTARA2   
27      2018-05-05 00:15:00   511.0                 curw_IBATTARA2   
28      2018-05-05 00:30:00   513.0                 curw_IBATTARA2   
29      2018-05-05 00:30:00    37.0                 curw_IBATTARA2   
...                     ...     ...                            ...   
147606  2018-06-10 23:30:00   460.0  curw_kottawa_dharmapala_north   
147607  2018-06-10 23:30:00  2011.0  curw_kottawa_dharmapala_north   
147608  2018-06-10 23:45:00  1159.0  curw_kottawa_dharmapala_north   
147609  2018-06-10 23:45:00  1681.0  curw_kottawa_dharmapala_north   
147610  2018-06-10 23:45:00  1685.0  curw_kottawa_dharmapala_north   
147611  2018-06-10 23:45:00  1179.0  curw_kottawa_dharmapala_north   
147612  2018-06-10 23:45:00   209.0  curw_kottawa_dharmapala_north   
147613  2018-06-10 23:45:00   229.0  curw_kottawa_dharmapala_north   
147614  2018-06-10 23:45:00   786.0  curw_kottawa_dharmapala_north   
147615  2018-06-10 23:45:00  2384.0  curw_kottawa_dharmapala_north   
147616  2018-06-10 23:45:00  2404.0  curw_kottawa_dharmapala_north   
147617  2018-06-10 23:45:00  1434.0  curw_kottawa_dharmapala_north   
147618  2018-06-10 23:45:00  1454.0  curw_kottawa_dharmapala_north   
147619  2018-06-10 23:45:00   456.0  curw_kottawa_dharmapala_north   
147620  2018-06-10 23:45:00   460.0  curw_kottawa_dharmapala_north   
147621  2018-06-10 23:45:00  2011.0  curw_kottawa_dharmapala_north   
147622  2018-06-10 23:45:00  1159.0  curw_kottawa_dharmapala_north   
147623  2018-06-10 23:45:00  1681.0  curw_kottawa_dharmapala_north   
147624  2018-06-10 23:45:00  1685.0  curw_kottawa_dharmapala_north   
147625  2018-06-10 23:45:00  1179.0  curw_kottawa_dharmapala_north   
147626  2018-06-10 23:45:00   209.0  curw_kottawa_dharmapala_north   
147627  2018-06-10 23:45:00   229.0  curw_kottawa_dharmapala_north   
147628  2018-06-10 23:45:00   786.0  curw_kottawa_dharmapala_north   
147629  2018-06-10 23:45:00  2384.0  curw_kottawa_dharmapala_north   
147630  2018-06-10 23:45:00  2404.0  curw_kottawa_dharmapala_north   
147631  2018-06-10 23:45:00 

Select RSL_MIN, FREQUENCY, PATH LENGTH as Features in the model

In [4]:
# data_file["hour"] = pd.to_datetime(data_file["date_time"]).dt.hour
data_file["Baseline_ATTN"] = data_file["Baseline"].sub(data_file["RSL_MIN"])
data_file["BaselineA_PathLen"] = data_file.apply(lambda x: x["Baseline_ATTN"]/x["PathLength"], axis=1)

In [5]:
data_file

date_time      ID                  PrecipStation  \
0       2018-05-05 00:00:00   513.0                 curw_IBATTARA2   
1       2018-05-05 00:00:00    37.0                 curw_IBATTARA2   
2       2018-05-05 00:00:00    70.0                 curw_IBATTARA2   
3       2018-05-05 00:00:00  2189.0                 curw_IBATTARA2   
4       2018-05-05 00:00:00  1706.0                 curw_IBATTARA2   
5       2018-05-05 00:00:00   173.0                 curw_IBATTARA2   
6       2018-05-05 00:00:00  1736.0                 curw_IBATTARA2   
7       2018-05-05 00:00:00  1738.0                 curw_IBATTARA2   
8       2018-05-05 00:00:00  1262.0                 curw_IBATTARA2   
9       2018-05-05 00:00:00  1295.0                 curw_IBATTARA2   
10      2018-05-05 00:00:00  1398.0                 curw_IBATTARA2   
11      2018-05-05 00:00:00   964.0                 curw_IBATTARA2   
12      2018-05-05 00:00:00   481.0                 curw_IBATTARA2   
13      2018-05-05 00:00:00   511.0                 curw_IBATTARA2   
14      2018-05-05 00:15:00   513.0                 curw_IBATTARA2   
15      2018-05-05 00:15:00    37.0                 curw_IBATTARA2   
16      2018-05-05 00:15:00    70.0                 curw_IBATTARA2   
17      2018-05-05 00:15:00  2189.0                 curw_IBATTARA2   
18      2018-05-05 00:15:00  1706.0                 curw_IBATTARA2   
19      2018-05-05 00:15:00   173.0                 curw_IBATTARA2   
20      2018-05-05 00:15:00  1736.0                 curw_IBATTARA2   
21      2018-05-05 00:15:00  1738.0                 curw_IBATTARA2   
22      2018-05-05 00:15:00  1262.0                 curw_IBATTARA2   
23      2018-05-05 00:15:00  1295.0                 curw_IBATTARA2   
24      2018-05-05 00:15:00  1398.0                 curw_IBATTARA2   
25      2018-05-05 00:15:00   964.0                 curw_IBATTARA2   
26      2018-05-05 00:15:00   481.0                 curw_IBATTARA2   
27      2018-05-05 00:15:00   511.0                 curw_IBATTARA2   
28      2018-05-05 00:30:00   513.0                 curw_IBATTARA2   
29      2018-05-05 00:30:00    37.0                 curw_IBATTARA2   
...                     ...     ...                            ...   
147606  2018-06-10 23:30:00   460.0  curw_kottawa_dharmapala_north   
147607  2018-06-10 23:30:00  2011.0  curw_kottawa_dharmapala_north   
147608  2018-06-10 23:45:00  1159.0  curw_kottawa_dharmapala_north   
147609  2018-06-10 23:45:00  1681.0  curw_kottawa_dharmapala_north   
147610  2018-06-10 23:45:00  1685.0  curw_kottawa_dharmapala_north   
147611  2018-06-10 23:45:00  1179.0  curw_kottawa_dharmapala_north   
147612  2018-06-10 23:45:00   209.0  curw_kottawa_dharmapala_north   
147613  2018-06-10 23:45:00   229.0  curw_kottawa_dharmapala_north   
147614  2018-06-10 23:45:00   786.0  curw_kottawa_dharmapala_north   
147615  2018-06-10 23:45:00  2384.0  curw_kottawa_dharmapala_north   
147616  2018-06-10 23:45:00  2404.0  curw_kottawa_dharmapala_north   
147617  2018-06-10 23:45:00  1434.0  curw_kottawa_dharmapala_north   
147618  2018-06-10 23:45:00  1454.0  curw_kottawa_dharmapala_north   
147619  2018-06-10 23:45:00   456.0  curw_kottawa_dharmapala_north   
147620  2018-06-10 23:45:00   460.0  curw_kottawa_dharmapala_north   
147621  2018-06-10 23:45:00  2011.0  curw_kottawa_dharmapala_north   
147622  2018-06-10 23:45:00  1159.0  curw_kottawa_dharmapala_north   
147623  2018-06-10 23:45:00  1681.0  curw_kottawa_dharmapala_north   
147624  2018-06-10 23:45:00  1685.0  curw_kottawa_dharmapala_north   
147625  2018-06-10 23:45:00  1179.0  curw_kottawa_dharmapala_north   
147626  2018-06-10 23:45:00   209.0  curw_kottawa_dharmapala_north   
147627  2018-06-10 23:45:00   229.0  curw_kottawa_dharmapala_north   
147628  2018-06-10 23:45:00   786.0  curw_kottawa_dharmapala_north   
147629  2018-06-10 23:45:00  2384.0  curw_kottawa_dharmapala_north   
147630  2018-06-10 23:45:00  2404.0  curw_kottawa_dharmapala_north   
147631  2018-06-10 23:45:00 

In [22]:
def calculate_time(row):
    if (row["RSL_MAX"] - row["RSL_MIN"]) == 0:
        return 15
    else:
        time  = 15*(row["RSL_MAX"] - row["RSL_AVG"]) / (row["RSL_MAX"] - row["RSL_MIN"])
        return time

In [23]:
data_file["refined"] = data_file.apply(lambda x: calculate_time(x)*x["Baseline_ATTN"], axis=1)
data_file["time"] = data_file.apply(lambda x: calculate_time(x), axis=1)

In [6]:
features = ["Baseline_ATTN","PathLength","FrequencyBand", "RSL_MAX", "TSL_MAX", "RSL_AVG"]

In [7]:
x_data = data_file[features]

In [31]:
x_data.shape

(364858, 6)

In [32]:
data_file

date_time      ID                  PrecipStation  \
0       2018-05-05 00:00:00   513.0                 curw_IBATTARA2   
1       2018-05-05 00:00:00    37.0                 curw_IBATTARA2   
2       2018-05-05 00:00:00    70.0                 curw_IBATTARA2   
3       2018-05-05 00:00:00  2189.0                 curw_IBATTARA2   
4       2018-05-05 00:00:00  1706.0                 curw_IBATTARA2   
5       2018-05-05 00:00:00   173.0                 curw_IBATTARA2   
6       2018-05-05 00:00:00  1736.0                 curw_IBATTARA2   
7       2018-05-05 00:00:00  1738.0                 curw_IBATTARA2   
8       2018-05-05 00:00:00  1262.0                 curw_IBATTARA2   
9       2018-05-05 00:00:00  1295.0                 curw_IBATTARA2   
10      2018-05-05 00:00:00  1398.0                 curw_IBATTARA2   
11      2018-05-05 00:00:00   964.0                 curw_IBATTARA2   
12      2018-05-05 00:00:00   481.0                 curw_IBATTARA2   
13      2018-05-05 00:00:00   511.0                 curw_IBATTARA2   
14      2018-05-05 00:15:00   513.0                 curw_IBATTARA2   
15      2018-05-05 00:15:00    37.0                 curw_IBATTARA2   
16      2018-05-05 00:15:00    70.0                 curw_IBATTARA2   
17      2018-05-05 00:15:00  2189.0                 curw_IBATTARA2   
18      2018-05-05 00:15:00  1706.0                 curw_IBATTARA2   
19      2018-05-05 00:15:00   173.0                 curw_IBATTARA2   
20      2018-05-05 00:15:00  1736.0                 curw_IBATTARA2   
21      2018-05-05 00:15:00  1738.0                 curw_IBATTARA2   
22      2018-05-05 00:15:00  1262.0                 curw_IBATTARA2   
23      2018-05-05 00:15:00  1295.0                 curw_IBATTARA2   
24      2018-05-05 00:15:00  1398.0                 curw_IBATTARA2   
25      2018-05-05 00:15:00   964.0                 curw_IBATTARA2   
26      2018-05-05 00:15:00   481.0                 curw_IBATTARA2   
27      2018-05-05 00:15:00   511.0                 curw_IBATTARA2   
28      2018-05-05 00:30:00   513.0                 curw_IBATTARA2   
29      2018-05-05 00:30:00    37.0                 curw_IBATTARA2   
...                     ...     ...                            ...   
147606  2018-06-10 23:30:00   460.0  curw_kottawa_dharmapala_north   
147607  2018-06-10 23:30:00  2011.0  curw_kottawa_dharmapala_north   
147608  2018-06-10 23:45:00  1159.0  curw_kottawa_dharmapala_north   
147609  2018-06-10 23:45:00  1681.0  curw_kottawa_dharmapala_north   
147610  2018-06-10 23:45:00  1685.0  curw_kottawa_dharmapala_north   
147611  2018-06-10 23:45:00  1179.0  curw_kottawa_dharmapala_north   
147612  2018-06-10 23:45:00   209.0  curw_kottawa_dharmapala_north   
147613  2018-06-10 23:45:00   229.0  curw_kottawa_dharmapala_north   
147614  2018-06-10 23:45:00   786.0  curw_kottawa_dharmapala_north   
147615  2018-06-10 23:45:00  2384.0  curw_kottawa_dharmapala_north   
147616  2018-06-10 23:45:00  2404.0  curw_kottawa_dharmapala_north   
147617  2018-06-10 23:45:00  1434.0  curw_kottawa_dharmapala_north   
147618  2018-06-10 23:45:00  1454.0  curw_kottawa_dharmapala_north   
147619  2018-06-10 23:45:00   456.0  curw_kottawa_dharmapala_north   
147620  2018-06-10 23:45:00   460.0  curw_kottawa_dharmapala_north   
147621  2018-06-10 23:45:00  2011.0  curw_kottawa_dharmapala_north   
147622  2018-06-10 23:45:00  1159.0  curw_kottawa_dharmapala_north   
147623  2018-06-10 23:45:00  1681.0  curw_kottawa_dharmapala_north   
147624  2018-06-10 23:45:00  1685.0  curw_kottawa_dharmapala_north   
147625  2018-06-10 23:45:00  1179.0  curw_kottawa_dharmapala_north   
147626  2018-06-10 23:45:00   209.0  curw_kottawa_dharmapala_north   
147627  2018-06-10 23:45:00   229.0  curw_kottawa_dharmapala_north   
147628  2018-06-10 23:45:00   786.0  curw_kottawa_dharmapala_north   
147629  2018-06-10 23:45:00  2384.0  curw_kottawa_dharmapala_north   
147630  2018-06-10 23:45:00  2404.0  curw_kottawa_dharmapala_north   
147631  2018-06-10 23:45:00 

In [8]:
# first we do  wet dry classification

data_file["wet_dry"] = data_file["class"].map({"A":"DRY","B":"WET","C":"WET","D":"WET","E":"WET","F":"WET","G":"WET","H":"WET"})

In [34]:
y_data = data_file["wet_dry"]

In [12]:
wet_dry_model = RandomForestClassifier(n_estimators=500)

In [14]:
# Oversampling
from imblearn.over_sampling import SMOTE

x_data, y_data = SMOTE().fit_sample(x_data, y_data)

In [60]:
# length_fixed_to_10_multiple = int(len(x_data)/10) * 10
# length_fixed_to_10_multiple

In [37]:
# x_data = x_data[:length_fixed_to_10_multiple]
# y_data = y_data[:length_fixed_to_10_multiple]

In [38]:
# scores = cross_val_score(wet_dry_model, x_data,y_data, cv=10, scoring="accuracy")
# print(scores)

[0.93523366 0.92366726 0.93992052 0.92092641 0.93734411 0.93885158
 0.93627518 0.9552967  0.92147458 0.9179937 ]


In [39]:
# scores.mean()

0.932698369192819

In [15]:
wet_dry_model.fit(x_data, y_data)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

Saving the model

In [16]:
import pickle
filename = "/home/cmlare/Data/Models/"+'RFClassifier_WetDry_RSLMAX_TSLMAX_BASELINE_MAX_oversampled.sav'
print("Saving model to "+ filename)
pickle.dump(wet_dry_model, open(filename, 'wb'))
print("Model Saved!")

Saving model to /home/cmlare/Data/Models/RFClassifier_WetDry_RSLMAX_TSLMAX_BASELINE_MAX_oversampled.sav
Model Saved!


In [2]:
# Load the model
import pickle
filename = "/home/cmlare/Data/Models/"+'RFClassifier_WetDry_RSLMAX_TSLMAX_BASELINE_MAX_oversampled.sav'
print("Loading model from "+ filename)
wet_dry_model = pickle.load(open(filename, 'rb'))

Loading model from /home/cmlare/Data/Models/RFClassifier_WetDry_RSLMAX_TSLMAX_BASELINE_MAX_oversampled.sav


In [9]:
wet_data_frame = data_file.loc[data_file.wet_dry == "WET"]
x_data = wet_data_frame[features]
y_data = wet_data_frame["class"]

In [14]:
# Oversampling
from imblearn.over_sampling import SMOTE

x_data, y_data = SMOTE().fit_sample(x_data, y_data)

wet_classifier = RandomForestClassifier(n_estimators=500)

wet_classifier.fit(x_data, y_data)

filename = "/home/cmlare/Data/Models/"+'RFClassifier_Wet_RSLMAX_TSLMAX_BASELINE_MAX_oversampled.sav'
print("Saving model to "+ filename)
pickle.dump(wet_classifier, open(filename, 'wb'))
print("Model Saved!")

Saving model to /home/cmlare/Data/Models/RFClassifier_Wet_RSLMAX_TSLMAX_BASELINE_MAX_oversampled.sav
Model Saved!


In [3]:
filename = "/home/cmlare/Data/Models/"+'RFClassifier_Wet_RSLMAX_TSLMAX_BASELINE_MAX_oversampled.sav'
print("Loading model from "+ filename)
wet_classifier = pickle.load(open(filename, 'rb'))

Loading model from /home/cmlare/Data/Models/RFClassifier_Wet_RSLMAX_TSLMAX_BASELINE_MAX_oversampled.sav


In [4]:
new_data = pd.read_csv("/home/cmlare/Data/RF Data/Processed/2018-06-11 to 2018-07-07_integrated_classified.csv")

In [6]:
new_data

date_time      ID                  PrecipStation  \
0       2018-06-11 00:00:00   513.0                 curw_IBATTARA2   
1       2018-06-11 00:00:00    37.0                 curw_IBATTARA2   
2       2018-06-11 00:00:00    70.0                 curw_IBATTARA2   
3       2018-06-11 00:00:00  2189.0                 curw_IBATTARA2   
4       2018-06-11 00:00:00  1706.0                 curw_IBATTARA2   
5       2018-06-11 00:00:00   173.0                 curw_IBATTARA2   
6       2018-06-11 00:00:00  1736.0                 curw_IBATTARA2   
7       2018-06-11 00:00:00  1738.0                 curw_IBATTARA2   
8       2018-06-11 00:00:00  1262.0                 curw_IBATTARA2   
9       2018-06-11 00:00:00  1295.0                 curw_IBATTARA2   
10      2018-06-11 00:00:00  1398.0                 curw_IBATTARA2   
11      2018-06-11 00:00:00   964.0                 curw_IBATTARA2   
12      2018-06-11 00:00:00   481.0                 curw_IBATTARA2   
13      2018-06-11 00:00:00   511.0                 curw_IBATTARA2   
14      2018-06-11 00:15:00   513.0                 curw_IBATTARA2   
15      2018-06-11 00:15:00    37.0                 curw_IBATTARA2   
16      2018-06-11 00:15:00    70.0                 curw_IBATTARA2   
17      2018-06-11 00:15:00  2189.0                 curw_IBATTARA2   
18      2018-06-11 00:15:00  1706.0                 curw_IBATTARA2   
19      2018-06-11 00:15:00   173.0                 curw_IBATTARA2   
20      2018-06-11 00:15:00  1736.0                 curw_IBATTARA2   
21      2018-06-11 00:15:00  1738.0                 curw_IBATTARA2   
22      2018-06-11 00:15:00  1262.0                 curw_IBATTARA2   
23      2018-06-11 00:15:00  1295.0                 curw_IBATTARA2   
24      2018-06-11 00:15:00  1398.0                 curw_IBATTARA2   
25      2018-06-11 00:15:00   964.0                 curw_IBATTARA2   
26      2018-06-11 00:15:00   481.0                 curw_IBATTARA2   
27      2018-06-11 00:15:00   511.0                 curw_IBATTARA2   
28      2018-06-11 00:30:00   513.0                 curw_IBATTARA2   
29      2018-06-11 00:30:00    37.0                 curw_IBATTARA2   
...                     ...     ...                            ...   
191120  2018-07-08 23:15:00   460.0  curw_kottawa_dharmapala_north   
191121  2018-07-08 23:15:00  2011.0  curw_kottawa_dharmapala_north   
191122  2018-07-08 23:30:00  1159.0  curw_kottawa_dharmapala_north   
191123  2018-07-08 23:30:00  1681.0  curw_kottawa_dharmapala_north   
191124  2018-07-08 23:30:00  1685.0  curw_kottawa_dharmapala_north   
191125  2018-07-08 23:30:00  1179.0  curw_kottawa_dharmapala_north   
191126  2018-07-08 23:30:00   209.0  curw_kottawa_dharmapala_north   
191127  2018-07-08 23:30:00   229.0  curw_kottawa_dharmapala_north   
191128  2018-07-08 23:30:00   786.0  curw_kottawa_dharmapala_north   
191129  2018-07-08 23:30:00  2384.0  curw_kottawa_dharmapala_north   
191130  2018-07-08 23:30:00  2404.0  curw_kottawa_dharmapala_north   
191131  2018-07-08 23:30:00  1434.0  curw_kottawa_dharmapala_north   
191132  2018-07-08 23:30:00  1454.0  curw_kottawa_dharmapala_north   
191133  2018-07-08 23:30:00   456.0  curw_kottawa_dharmapala_north   
191134  2018-07-08 23:30:00   460.0  curw_kottawa_dharmapala_north   
191135  2018-07-08 23:30:00  2011.0  curw_kottawa_dharmapala_north   
191136  2018-07-08 23:45:00  1159.0  curw_kottawa_dharmapala_north   
191137  2018-07-08 23:45:00  1681.0  curw_kottawa_dharmapala_north   
191138  2018-07-08 23:45:00  1685.0  curw_kottawa_dharmapala_north   
191139  2018-07-08 23:45:00  1179.0  curw_kottawa_dharmapala_north   
191140  2018-07-08 23:45:00   209.0  curw_kottawa_dharmapala_north   
191141  2018-07-08 23:45:00   229.0  curw_kottawa_dharmapala_north   
191142  2018-07-08 23:45:00   786.0  curw_kottawa_dharmapala_north   
191143  2018-07-08 23:45:00  2384.0  curw_kottawa_dharmapala_north   
191144  2018-07-08 23:45:00  2404.0  curw_kottawa_dharmapala_north   
191145  2018-07-08 23:45:00 

In [5]:
data_file = new_data.loc[lambda x: x["distance"] < 5]

# data_file["hour"] = pd.to_datetime(data_file["date_time"]).dt.hour
data_file["Baseline_ATTN"] = data_file["Baseline"].sub(data_file["RSL_MIN"])
data_file["BaselineA_PathLen"] = data_file.apply(lambda x: x["Baseline_ATTN"]/x["PathLength"], axis=1)

features = ["Baseline_ATTN","PathLength","FrequencyBand", "RSL_MAX", "TSL_MAX", "RSL_AVG"]
data_file["wet_dry"] = data_file["class"].map({"A":"DRY","B":"WET","C":"WET","D":"WET","E":"WET","F":"WET","G":"WET","H":"WET"})

# def calculate_time(row):
#     if (row["RSL_MAX"] - row["RSL_MIN"]) == 0:
#         return 15
#     else:
#         time  = 15*(row["RSL_MAX"] - row["RSL_AVG"]) / (row["RSL_MAX"] - row["RSL_MIN"])
#         return time
    
# data_file_less_5["refined"] = data_file_less_5.apply(lambda x: calculate_time(x)*x["Baseline_ATTN"], axis=1)
# data_file_less_5["time"] = data_file_less_5.apply(lambda x: calculate_time(x), axis=1)

x_data_new = data_file[features]
y_data_new = data_file["wet_dry"]

In [6]:
data_file

date_time      ID                  PrecipStation  \
0       2018-06-11 00:00:00   513.0                 curw_IBATTARA2   
1       2018-06-11 00:00:00    37.0                 curw_IBATTARA2   
2       2018-06-11 00:00:00    70.0                 curw_IBATTARA2   
3       2018-06-11 00:00:00  2189.0                 curw_IBATTARA2   
4       2018-06-11 00:00:00  1706.0                 curw_IBATTARA2   
5       2018-06-11 00:00:00   173.0                 curw_IBATTARA2   
6       2018-06-11 00:00:00  1736.0                 curw_IBATTARA2   
7       2018-06-11 00:00:00  1738.0                 curw_IBATTARA2   
8       2018-06-11 00:00:00  1262.0                 curw_IBATTARA2   
9       2018-06-11 00:00:00  1295.0                 curw_IBATTARA2   
10      2018-06-11 00:00:00  1398.0                 curw_IBATTARA2   
11      2018-06-11 00:00:00   964.0                 curw_IBATTARA2   
12      2018-06-11 00:00:00   481.0                 curw_IBATTARA2   
13      2018-06-11 00:00:00   511.0                 curw_IBATTARA2   
14      2018-06-11 00:15:00   513.0                 curw_IBATTARA2   
15      2018-06-11 00:15:00    37.0                 curw_IBATTARA2   
16      2018-06-11 00:15:00    70.0                 curw_IBATTARA2   
17      2018-06-11 00:15:00  2189.0                 curw_IBATTARA2   
18      2018-06-11 00:15:00  1706.0                 curw_IBATTARA2   
19      2018-06-11 00:15:00   173.0                 curw_IBATTARA2   
20      2018-06-11 00:15:00  1736.0                 curw_IBATTARA2   
21      2018-06-11 00:15:00  1738.0                 curw_IBATTARA2   
22      2018-06-11 00:15:00  1262.0                 curw_IBATTARA2   
23      2018-06-11 00:15:00  1295.0                 curw_IBATTARA2   
24      2018-06-11 00:15:00  1398.0                 curw_IBATTARA2   
25      2018-06-11 00:15:00   964.0                 curw_IBATTARA2   
26      2018-06-11 00:15:00   481.0                 curw_IBATTARA2   
27      2018-06-11 00:15:00   511.0                 curw_IBATTARA2   
28      2018-06-11 00:30:00   513.0                 curw_IBATTARA2   
29      2018-06-11 00:30:00    37.0                 curw_IBATTARA2   
...                     ...     ...                            ...   
191120  2018-07-08 23:15:00   460.0  curw_kottawa_dharmapala_north   
191121  2018-07-08 23:15:00  2011.0  curw_kottawa_dharmapala_north   
191122  2018-07-08 23:30:00  1159.0  curw_kottawa_dharmapala_north   
191123  2018-07-08 23:30:00  1681.0  curw_kottawa_dharmapala_north   
191124  2018-07-08 23:30:00  1685.0  curw_kottawa_dharmapala_north   
191125  2018-07-08 23:30:00  1179.0  curw_kottawa_dharmapala_north   
191126  2018-07-08 23:30:00   209.0  curw_kottawa_dharmapala_north   
191127  2018-07-08 23:30:00   229.0  curw_kottawa_dharmapala_north   
191128  2018-07-08 23:30:00   786.0  curw_kottawa_dharmapala_north   
191129  2018-07-08 23:30:00  2384.0  curw_kottawa_dharmapala_north   
191130  2018-07-08 23:30:00  2404.0  curw_kottawa_dharmapala_north   
191131  2018-07-08 23:30:00  1434.0  curw_kottawa_dharmapala_north   
191132  2018-07-08 23:30:00  1454.0  curw_kottawa_dharmapala_north   
191133  2018-07-08 23:30:00   456.0  curw_kottawa_dharmapala_north   
191134  2018-07-08 23:30:00   460.0  curw_kottawa_dharmapala_north   
191135  2018-07-08 23:30:00  2011.0  curw_kottawa_dharmapala_north   
191136  2018-07-08 23:45:00  1159.0  curw_kottawa_dharmapala_north   
191137  2018-07-08 23:45:00  1681.0  curw_kottawa_dharmapala_north   
191138  2018-07-08 23:45:00  1685.0  curw_kottawa_dharmapala_north   
191139  2018-07-08 23:45:00  1179.0  curw_kottawa_dharmapala_north   
191140  2018-07-08 23:45:00   209.0  curw_kottawa_dharmapala_north   
191141  2018-07-08 23:45:00   229.0  curw_kottawa_dharmapala_north   
191142  2018-07-08 23:45:00   786.0  curw_kottawa_dharmapala_north   
191143  2018-07-08 23:45:00  2384.0  curw_kottawa_dharmapala_north   
191144  2018-07-08 23:45:00  2404.0  curw_kottawa_dharmapala_north   
191145  2018-07-08 23:45:00 

In [7]:
y_predicted = wet_dry_model.predict(x_data_new)

In [8]:
confusion_matrix(y_data_new, y_predicted)

array([[179650,   6570],
       [  2522,   2408]])

In [9]:
print(classification_report(y_data_new, y_predicted))

             precision    recall  f1-score   support

        DRY       0.99      0.96      0.98    186220
        WET       0.27      0.49      0.35      4930

avg / total       0.97      0.95      0.96    191150



In [8]:
data_file["predicted_wet_dry"] = y_predicted

In [9]:
wet_data = data_file.loc[data_file.predicted_wet_dry == "WET"]
dry_data = data_file.loc[data_file.predicted_wet_dry == "DRY"]

data_file_combined = pd.concat([wet_data, dry_data])

In [20]:
y_predicted_dry = dry_data["class"]

x_data_wet = wet_data[features]

In [11]:
y_data_wet_predicted = wet_classifier.predict(x_data_wet)

In [12]:
y_data_wet_actual = data_file_combined["class"]

In [21]:
y_predicted_dry = y_predicted_dry.values

In [22]:
y_predicted_dry

array(['A', 'A', 'A', ..., 'A', 'A', 'A'], dtype=object)

In [25]:
y_data_wet_predicted_all = np.concatenate((y_data_wet_predicted, y_predicted_dry))

In [26]:
y_data_wet_predicted_all

array(['E', 'E', 'D', ..., 'A', 'A', 'A'], dtype=object)

In [28]:
print(confusion_matrix(y_data_wet_actual, y_data_wet_predicted_all))

[[179650   3111    851   1297    597    320    163    231]
 [     0   2219    201    204    128     52     28     26]
 [     0    114    415     97     73     17      6      8]
 [     0     49    116    469    108     33     26     57]
 [     0     28     20     52    113     38     33     40]
 [     0      1      7      4      6     20      6      0]
 [     0      5      3      8     20      6     22     36]
 [     0      0      0      1      3      4      2      6]]


In [29]:
print(classification_report(y_data_wet_actual, y_data_wet_predicted_all))

             precision    recall  f1-score   support

          A       1.00      0.96      0.98    186220
          B       0.40      0.78      0.53      2858
          C       0.26      0.57      0.35       730
          D       0.22      0.55      0.31       858
          E       0.11      0.35      0.16       324
          F       0.04      0.45      0.07        44
          G       0.08      0.22      0.11       100
          H       0.01      0.38      0.03        16

avg / total       0.98      0.96      0.97    191150



calculated baseline

with refined baseline attenuation

In [48]:
data_file_less_5 = new_data.loc[lambda x: x["distance"] < 5]

data_file_less_5["Baseline_ATTN"] = data_file_less_5["Baseline"].sub(data_file_less_5["RSL_MIN"])

features = ["refined", "PathLength"]

def calculate_time(row):
    if (row["RSL_MAX"] - row["RSL_MIN"]) == 0:
        return 15
    else:
        time  = 15*(row["RSL_MAX"] - row["RSL_AVG"]) / (row["RSL_MAX"] - row["RSL_MIN"])
        return time
    
data_file_less_5["refined"] = data_file_less_5.apply(lambda x: calculate_time(x)*x["Baseline_ATTN"], axis=1)
data_file_less_5["time"] = data_file_less_5.apply(lambda x: calculate_time(x), axis=1)

x_data_new = data_file_less_5[features]
y_data_new = data_file_less_5["class"]

y_predicted = random_forest_classifier.predict(x_data_new)

/usr/lib/python3/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/lib/python3/dist-packages/ipykernel_launcher.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/usr/lib/python3/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.py

In [49]:
y_predicted = random_forest_classifier.predict(x_data_new)

In [50]:
confusion_matrix(y_data_new, y_predicted)

array([[93012, 11894,  4706, 15178,  6730,  4718,  4831, 15033],
       [ 1323,   740,   171,   405,   349,   427,   130,   263],
       [  126,   127,    23,    56,    51,   135,    37,    37],
       [  403,   134,    32,   122,    80,   140,    39,   182],
       [  185,    50,    11,    39,    28,    42,    28,   137],
       [  138,    10,     0,     8,    11,    41,    15,    37],
       [    0,     0,     0,     0,     0,     0,     0,     0],
       [    0,     0,     0,     0,     0,     0,     0,     0]])

In [51]:
print(classification_report(y_data_new, y_predicted))

             precision    recall  f1-score   support

          A       0.98      0.60      0.74    156102
          B       0.06      0.19      0.09      3808
          C       0.00      0.04      0.01       592
          D       0.01      0.11      0.01      1132
          E       0.00      0.05      0.01       520
          F       0.01      0.16      0.01       260
          G       0.00      0.00      0.00         0
          H       0.00      0.00      0.00         0

avg / total       0.94      0.58      0.71    162414



/home/cmlare/.local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
